### ISSUE TITLE
Uncatched exception: merlin 3.4.2, ocaml 4.11.1

### ISSUE THREAD

**Issue by FardaleM** [ocaml/merlin#1222]
On OCaml 4.11.1, merlin 3.4.2 crash on the following code:
```ocaml
let minimal : type a. 'a t
```

with the following error:
```
Erreur détectée en traitant function merlin#Register[136]..merlin#LoadProject[2]..provider#python3#Call :
ligne   18 :
Error invoking 'python_execute' on channel 3 (python3-script-host):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/fardale/.opam/base/share/merlin/vim/autoload/merlin.py", line 770, in setup_merlin
    result = command("check-configuration")
  File "/home/fardale/.opam/base/share/merlin/vim/autoload/merlin.py", line 189, in command
    return command2(args)
  File "/home/fardale/.opam/base/share/merlin/vim/autoload/merlin.py", line 184, in command2
    raise Error(value)
merlin.Error: "In this scoped type, variable 'a is reserved for the local type a."
Error invoking 'python_execute' on channel 3 (python3-script-host):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/fardale/.opam/base/share/merlin/vim/autoload/merlin.py", line 770, in setup_merlin
    result = command("check-configuration")
  File "/home/fardale/.opam/base/share/merlin/vim/autoload/merlin.py", line 189, in command
    return command2(args)
  File "/home/fardale/.opam/base/share/merlin/vim/autoload/merlin.py", line 184, in command2
    raise Error(value)
merlin.Error: "In this scoped type, variable 'a is reserved for the local type a."
```

**Comment by voodoos** [comment]
Thank you for your report !
PR #1223 should fix it.
