### ISSUE TITLE
:MerlinOccurrencesProjectWide fails with KeyError

### ISSUE THREAD

**Issue by talex5** [ocaml/merlin#1832]
I tried using this new feature on Eio (e.g. on `statx_works` at https://github.com/ocaml-multicore/eio/blob/d2a3e21bc47dd7a6c482f4c61f9e00c1a39922a9/lib_eio_linux/sched.ml#L12; many other places fail too). I got:

```
Error detected while processing function merlin#OccurrencesProjectWide:
line    3:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/.opam/5.2.0-fp/share/merlin/vim/autoload/merlin.py", line 548, in vim_occurrences
    for pos in with_text_previews(lst):
  File "/home/user/.opam/5.2.0-fp/share/merlin/vim/autoload/merlin.py", line 536, in with_text_previews
    text = preview_lines_by_file[oc['file']][lnum]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
KeyError: 12 
```
`preview_lines_by_file[oc['file']]` has entries for 526 and 527 (the other two uses in the file), but not for 12 (the definition).

```python
occurs = [
  {'file': '/home/user/work/eio/lib_eio_linux/sched.ml',
   'start': {'line': 12, 'col': 4},
   'end': {'line': 12, 'col': 15}},
  {'file': '/home/user/work/eio/lib_eio_linux/eio_linux.ml',
   'start': {'line': 421, 'col': 14},
   'end': {'line': 421, 'col': 25}},
  {'file': '/home/user/work/eio/lib_eio_linux/sched.ml',
   'start': {'line': 526, 'col': 14},
   'end': {'line': 526, 'col': 25}},
  {'file': '/home/user/work/eio/lib_eio_linux/sched.ml',
   'start': {'line': 527, 'col': 8},
   'end': {'line': 527, 'col': 19}}
]
```

The Python docs say:
> Generally, the iterable needs to already be sorted on the same key function.

I tried adding this to the start of the function, and that seemed to fix it:
```python
occurs.sort(key = lambda oc: oc.get('file'))
```

**Comment by voodoos** [comment]
Thanks for the report and investigation @talex5, I am not familiar with the vim implementation, so forwarding to @Julow

**Comment by Julow** [comment]
Indeed, that was a misunderstanding of how `itertools.groupby` works and sorting fixes it :) Could you open a PR ?
