### ISSUE TITLE
PPX debugging

### ISSUE THREAD

**Issue by xguerin** [ocaml/merlin#637]
I have a PPX that works fine during compilation but misbehave within `merlin`:

```
(merlin) backtrace:
Error detected while processing function <SNR>118_BufEnterHook[9]..<SNR>118_UpdateErrors[15]..<SNR>118_CacheErrors[39]..278[1]..277[24]..SyntaxCheckers_ocaml_merlin_GetLocList[1]..merlin#ErrorLocList:
line    8:
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/Users/xguerin/.opam/4.04.0/share/merlin/vim/autoload/merlin.py", line 399, in vim_loclist
    errors = query("errors")
  File "/Users/xguerin/.opam/4.04.0/share/merlin/vim/autoload/merlin.py", line 211, in query
    return command(*cmd)
  File "/Users/xguerin/.opam/4.04.0/share/merlin/vim/autoload/merlin.py", line 201, in command
    return merlin_process().command(context(cmd))
  File "/Users/xguerin/.opam/4.04.0/share/merlin/vim/autoload/merlin.py", line 168, in command
    raise Error(value)
merlin.Error: {u'message': u"Error while running external preprocessor\nCommand line: /Users/xguerin/.opam/4.04.0/lib/ppx_import/./ppx_import '/var/folders/b3/ys8hj_f17b70c88p3cgc7nd00000gn/T/camlppxcb1305' '/var/folders/b3/ys8hj_f17b70c8
8p3cgc7nd00000gn/T/camlppxe6ca33' 1>/dev/null 2>/dev/null", u'valid': True, u'type': u'type', u'sub': []}
Error detected while processing function <SNR>118_BufEnterHook[9]..<SNR>118_UpdateErrors[15]..<SNR>118_CacheErrors:
line   39:
E170: Missing :endfor
Error detected while processing function <SNR>118_BufEnterHook[9]..<SNR>118_UpdateErrors:
line   15:
E171: Missing :endif
Error detected while processing function <SNR>118_BufEnterHook:
line    9:
E171: Missing :endif
```

What is the best approach to debug such behavior ?

**Comment by xguerin** [comment]
To reproduce:

1. Install `ppx_import` v1.2
2. Use the following as `test.mli`:

```ocaml
type t = int * string
```

3. Use the following as `test.ml`

```ocaml
type t = [%import: Test.t]
```

4. Use the following as `.merlin`

```
PKG ppx_import
S .
B .
```

4. Compile `test.mli`

```
ocamlfind c test.mli
```

5. Open `test.ml` with `vim`, and try to save

**Comment by trefis** [comment]
I followed the steps you've given and cannot reproduce.
I am using the git master version of Merlin, which you might not?

**Comment by xguerin** [comment]
Nope, I'm using OPAM version of Merlin. I'll try with the git master version.
