### ISSUE TITLE
TypeOf error with NeoVim

### ISSUE THREAD

**Issue by ns-cweber** [ocaml/merlin#662]
I'm having an error with the type checking in NeoVim, specifically that I get this stack trace:

```py
Error detected while processing function merlin#TypeOf[5]..<SNR>62_ShowTypeEnclosing[27]..merlin_type#Show[9]..<SNR>73_RecordType[38]..provider#python#Call:
line   18:
IndexError('list index out of range',)
Traceback (most recent call last):
  File "/Users/cweber/Library/Python/2.7/lib/python/site-packages/neovim/msgpack_rpc/session.py", line 185, in handler
    rv = self._request_cb(name, args)
  File "/Users/cweber/Library/Python/2.7/lib/python/site-packages/neovim/api/nvim.py", line 151, in filter_request_cb
    result = request_cb(self._from_nvim(name), args)
  File "/Users/cweber/Library/Python/2.7/lib/python/site-packages/neovim/plugin/host.py", line 74, in _on_request
    rv = handler(*args)
  File "/Users/cweber/Library/Python/2.7/lib/python/site-packages/neovim/plugin/script_host.py", line 75, in python_execute
    exec(script, self.module.__dict__)
  File "<string>", line 12, in <module>
IndexError: list index out of range
```

merlin version 2.5.0; neovim 0.2.0

Here's the output of `$MERLIN_LOG`:

```
# 0.00 frontend - input
[ "protocol", "version", 3 ]
# 0.00 dot_merlin - load filenames
[]
# 0.00 frontend - output
{
  "class": "return",
  "value": {
    "selected": 3,
    "latest": 3,
    "merlin":
      "The Merlin toolkit version git-9625b225eef3677aa477da659f097e65e5f54468, for Ocaml 4.02.3"
  },
  "notifications": []
}
# 0.00 frontend - input
{
  "query": [ "project", "get" ],
  "context": [
    "auto", "/Users/cweber/Projects/src/temp/reasonml/llama/src/main.re"
  ]
}
# 0.00 dot_merlin - load filenames
[ "/Users/cweber/Projects/src/temp/reasonml/llama/src" ]
# 0.00 frontend - output
{
  "class": "return",
  "value": {
    "result": [ "/Users/cweber/Projects/src/temp/reasonml/llama/.merlin" ]
  },
  "notifications": []
}
# 0.00 frontend - input
{
  "query": [
    "tell", "start", "end",
    "open Yojson;\nopen Yojson.Basic.Util;\nopen Unix;\n\ninclude Result;\n\nlet run (command: string) :result unit Unix.process_status => {\n    let st = Unix.system command;\n    switch st {\n    | Unix.WEXITED code => code == 0 ? OK() : Error(st)\n    | _ => Error(st)\n    }\n};\n\nmodule Project = {\n    type project = {name: string, executable: string, packages: list string};\n\n    let from_json json => {\n        name: json |> member \"name\" |> to_string,\n        executable: json |> member \"executable\" |> to_string,\n        packages: json |> member \"packages\" |> to_list |> filter_string,\n    };\n\n    let build project => {\n        let stdlib = [\"unix\"];\n        let rec external_packages packages => switch packages {\n        | [] => []\n        | [head, ...tail] => (List.exists (fun i => i != head) stdlib)\n                ? [head, ...external_packages tail]\n                : external_packages tail\n        };\n        let install_commands = List.map\n            (fun pkg => \"opam install \" ^ pkg)\n            (external_packages project.packages);\n        let package_list = String.concat \",\" project.packages;\n        let build_commands = [\n            \"rebuild -pkgs \" ^ package_list ^ \" -I src ./src/main.native\",\n            \"mv main.native \" ^ project.executable,\n        ];\n        mapm (install_commands @ build_commands) run\n    };\n};\n\nlet json = Yojson.Basic.from_channel (open_in \"./project.json\");\nlet project = Project.from_json json;\n\nswitch (Project.build project) {\n| OK v => print_string \"OK!\\n\"\n| Error st => switch st {\n    | Unix.WEXITED code => print_string (\"ERR CODE: \" ^ (string_of_int code) ^ \"\\n\")\n    | _ => print_string \"SOME OTHER ERR\\n\"\n    }\n};\n"
  ],
  "context": [
    "auto", "/Users/cweber/Projects/src/temp/reasonml/llama/src/main.re"
  ]
}
# 0.00 dot_merlin - update filenames
[ "/Users/cweber/Projects/src/temp/reasonml/llama/src" ]
# 0.00 dot_merlin - update files
[ "/Users/cweber/Projects/src/temp/reasonml/llama/.merlin" ]
# 0.00 frontend - output
{ "class": "return", "value": true, "notifications": [] }
# 0.00 frontend - input
{
  "query": [ "errors" ],
  "context": [
    "auto", "/Users/cweber/Projects/src/temp/reasonml/llama/src/main.re"
  ]
}
# 0.02 frontend - output
{ "class": "return", "value": [], "notifications": [] }
# 0.02 frontend - input
{
  "query": [ "type", "enclosing", "at", { "line": 7, "col": 4 } ],
  "context": [
    "auto", "/Users/cweber/Projects/src/temp/reasonml/llama/src/main.re"
  ]
}
# 0.02 frontend - output
{
  "class": "return",
  "value": [
    {
      "start": { "line": 7, "col": 4 },
      "end": { "line": 7, "col": 7 },
      "type": "string => result unit Unix.process_status",
      "tail": "no"
    }
  ],
  "notifications": []
}
```

**Comment by bassjacob** [comment]
Hi, I have the same issue. Discussed in the reason discord, and it appears that setting `let g:merlin_type_history_height = 0` fixes this, suggesting that the error is coming from https://github.com/ocaml/merlin/blob/master/vim/merlin/autoload/merlin.vim#L213

If we trace that call, I think the failing function is https://github.com/ocaml/merlin/blob/master/vim/merlin/autoload/merlin_type.vim#L113 where it accesses an index that doesn't exist of bufwinnr.

**Comment by bassjacob** [comment]
I have a patch incoming.
