### ISSUE TITLE
Merlin LoadProject error

### ISSUE THREAD

**Issue by pe200012** [ocaml/merlin#664]
When I open vim, merlin show the message below

处理 function merlin#Register[135]..merlin#LoadProject 时发生错误:
第    2 行:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/pe200012/.vim/bundle/merlin/vim/merlin/autoload/merlin.py", line 696, in setup_merlin
    result = command("check-configuration")
  File "/home/pe200012/.vim/bundle/merlin/vim/merlin/autoload/merlin.py", line 186, in command
    return command2(args)
  File "/home/pe200012/.vim/bundle/merlin/vim/merlin/autoload/merlin.py", line 170, in command2
    result = json.loads(merlin_exec(cmdline,input=content))
  File "/usr/lib64/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

What should I do?

**Comment by pe200012** [comment]
Ok, I found out the solution. "DO NOT use Vundle".
