### ISSUE TITLE
Python error in MerlinDocument

### ISSUE THREAD

**Issue by copy** [ocaml/merlin#683]
When using `:MerlinDocument` (without arguments), I'm getting the following error on merlin 3.0. The version with an argument works (i.e. `:MerlinDocument Lwt.bind`), but ignores its argument (it behaves like `:MerlinDocument`).

```
Error detected while processing function merlin#Document:
line    4:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/media/samsung/opam/4.04.1/share/merlin/vim/autoload/merlin.py", line 436, in vim_document_under_cursor
    vim_document_at_cursor(None)
  File "/media/samsung/opam/4.04.1/share/merlin/vim/autoload/merlin.py", line 433, in vim_document_at_cursor
    command_document(path, vim.current.window.cursor)
  File "/media/samsung/opam/4.04.1/share/merlin/vim/autoload/merlin.py", line 238, in command_document
    print(command2(cmd))
  File "/media/samsung/opam/4.04.1/share/merlin/vim/autoload/merlin.py", line 172, in command2
    result = json.loads(merlin_exec(cmdline,input=content))
  File "/media/samsung/opam/4.04.1/share/merlin/vim/autoload/merlin.py", line 133, in merlin_exec
    env=env
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

**Comment by trefis** [comment]
This is now fixed on master.
Thanks for the report!
