### ISSUE TITLE
vim_next_enclosing breaks when already at the root of the document

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [ocaml/merlin#770]
In Vim, given the following document, with the cursor on the `1`,

    let i = 123 in

An initial `<LocalLeader>t` yields, as expected, `int` — but a following `<LocalLeader>n` to select the “next enclosing” type-signature spits up the following Python error:

```
Error detected while processing function merlin#GrowEnclosing[1]..provider#python#Call:
line   18:
Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/Users/ec/Documents/Code/Source/merlin/vim/merlin/autoload/merlin.py", line 705, in vim_next_enclosing
    return vim_current_enclosing()

  File "/Users/ec/Documents/Code/Source/merlin/vim/merlin/autoload/merlin.py", line 695, in vim_current_enclosing
    tmp['type'] = enclosing_type_text(tmp)

  File "/Users/ec/Documents/Code/Source/merlin/vim/merlin/autoload/merlin.py", line 686, in enclosing_type_text
    return types[record['type']]['type']

IndexError: list index out of range
Error detected while processing function merlin#GrowEnclosing:
line    2:
E121: Undefined variable: l:type
E116: Invalid arguments for function <SNR>142_ShowTypeEnclosing
```

**Comment by ELLIOTTCABLE** [comment]
Oop, accidentally a duplicate of my own #732. 🙄
