### ISSUE TITLE
Installation did not work in Vim (help appreciated)

### ISSUE THREAD

**Issue by jordwalke** [ocaml/merlin#88]
I completed the instructions in the README.
1. Installed OPAM (and version 4.00.1 Ocaml) - Made sure to "switch" to the right version.
2. OPAM installed merlin. (I saw no errors in installation)
3. Setup my vim runtime path as noted in the README (and open issues):

```
let s:ocamlmerlin=substitute(system('opam config var share'),'\n$','','') . "/ocamlmerlin"
execute "set rtp+=".s:ocamlmerlin."/vim"
execute "set rtp+=".s:ocamlmerlin."/vimbufsync"
```

When opening a `.ml` file, I get this error:

```
iError detected while processing function merlin#LoadProject..merlin#FindOcamlMerlin:
line    8:
ocamlmerlin not found!
line   12:
E716: Key not present in Dictionary: ocamlmerlin_path
E15: Invalid expression: s:c.ocamlmerlin_path
Failed starting ocamlmerlin. Please ensure that ocamlmerlin binary            is executable.
Error detected while processing function merlin#LoadProject:
line    1:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/me/.opam/4.00.1/share/ocamlmerlin/vim/autoload/merlin.py", line 65, in send_command
    restart()
  File "/Users/me/.opam/4.00.1/share/ocamlmerlin/vim/autoload/merlin.py", line 60, in restart
    raise e
OSError: [Errno 2] No such file or directory
Error detected while processing function merlin#LoadProject..merlin#FindOcamlMerlin:
line    8:
ocamlmerlin not found!
line   12:
E716: Key not present in Dictionary: ocamlmerlin_path
E15: Invalid expression: s:c.ocamlmerlin_path
Failed starting ocamlmerlin. Please ensure that ocamlmerlin binary            is executable.
Error detected while processing function merlin#LoadProject:
line    2:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/me/.opam/4.00.1/share/ocamlmerlin/vim/autoload/merlin.py", line 480, in load_project
    fnames = catch_and_print(lambda: send_command("project","find",directory))
  File "/Users/me/.opam/4.00.1/share/ocamlmerlin/vim/autoload/merlin.py", line 116, in catch_and_print
    return f()
  File "/Users/me/.opam/4.00.1/share/ocamlmerlin/vim/autoload/merlin.py", line 480, in <lambda>
    fnames = catch_and_print(lambda: send_command("project","find",directory))
  File "/Users/me/.opam/4.00.1/share/ocamlmerlin/vim/autoload/merlin.py", line 65, in send_command
    restart()
  File "/Users/me/.opam/4.00.1/share/ocamlmerlin/vim/autoload/merlin.py", line 60, in restart
    raise e
OSError: [Errno 2] No such file or directory
```

**Comment by XVilka** [comment]
Met the same error today
