### ISSUE TITLE
merlin.Failure: 'Graph.add: class type already defined'

### ISSUE THREAD

**Issue by ygrek** [ocaml/merlin#907]
Observing the following stack trace 
```
Error detected while processing function <SNR>40_BufWritePostHook[4]..<SNR>40_UpdateErrors[15]..<SNR>40_CacheErrors[39]..16[1]..15[24]..SyntaxCheckers_ocaml_me
rlin_GetLocList[1]..merlin#ErrorLocList:
line    8:
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/home/ygrek/.opam/a/share/merlin/vim/autoload/merlin.py", line 398, in vim_loclist
    errors = command("errors")
  File "/home/ygrek/.opam/a/share/merlin/vim/autoload/merlin.py", line 188, in command
    return command2(args)
  File "/home/ygrek/.opam/a/share/merlin/vim/autoload/merlin.py", line 181, in command2
    raise Failure(value)
merlin.Failure: 'Graph.add: class type already defined'
Error detected while processing function <SNR>40_BufWritePostHook[4]..<SNR>40_UpdateErrors[15]..<SNR>40_CacheErrors:
line   39:
E170: Missing :endfor
Error detected while processing function <SNR>40_BufWritePostHook[4]..<SNR>40_UpdateErrors:
line   15:
E171: Missing :endif
```
when trying to save this code : 
```
class test ?a =
object
  method b = c
end

(* the following cases do not trigger error *)

class test a =
object
  method b = c
end

class test ?a =
object
  method b = ()
end
```

related to #843 and #670

**Comment by trefis** [comment]
Can you confirm which version of OCaml this is happening with?
